const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let state=JSON.parse(localStorage.getItem("primeXState")||'{"completed":{},"tasks":[],"pyqs":[],"focus":0,"streak":0}');
let currentSub="Physics", timer=null, totalSec=1500, leftSec=1500;

function save(){localStorage.setItem("primeXState",JSON.stringify(state));}
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1800)}
function showPage(id){$$(".page").forEach(p=>p.classList.remove("active"));$("#"+id).classList.add("active");$$(".nav").forEach(n=>n.classList.toggle("active",n.dataset.page===id));$("#pageTitle").textContent={dashboard:"Dashboard",syllabus:"Syllabus",planner:"Planner",pyq:"PYQ Tracker",timer:"Focus Timer",analytics:"Analytics"}[id]||id; if(id==="dashboard")renderDash();if(id==="analytics")renderAnalytics();}
$$(".nav").forEach(n=>n.onclick=()=>showPage(n.dataset.page));
$("#today").textContent=new Intl.DateTimeFormat("en-IN",{weekday:"short",day:"2-digit",month:"short"}).format(new Date());

function progress(sub){let arr=SYLLABUS[sub],d=arr.filter((_,i)=>state.completed[sub+"-"+i]).length;return Math.round(d/arr.length*100)}
function renderSyllabus(){let q=$("#syllabusSearch").value.toLowerCase();let arr=SYLLABUS[currentSub], html="";arr.forEach((u,i)=>{let done=!!state.completed[currentSub+"-"+i];if(q&&!u.join(" ").toLowerCase().includes(q))return;html+=`<label class="unit ${done?"done":""}"><input type="checkbox" ${done?"checked":""} data-i="${i}"><div><h4>UNIT ${i+1} · ${u[0]}</h4><p>${u[1]}</p></div></label>`});$("#syllabusList").innerHTML=html||'<div class="empty">No matching unit.</div>';$("#syllabusProgress").textContent=`${progress(currentSub)}% complete`;$$("#syllabusList input").forEach(c=>c.onchange=()=>{state.completed[currentSub+"-"+c.dataset.i]=c.checked;save();renderSyllabus();renderDash();toast(c.checked?"Unit completed ✓":"Unit reopened");});}
$$(".tab").forEach(t=>t.onclick=()=>{$$(".tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");currentSub=t.dataset.sub;renderSyllabus()});$("#syllabusSearch").oninput=renderSyllabus;

function openTaskModal(){openModal(`<h2>Add study task</h2><div class="form"><label>TASK</label><input id="fTask" placeholder="e.g. Electrostatics PYQs"><label>SUBJECT</label><select id="fSub"><option>Physics</option><option>Chemistry</option><option>Mathematics</option></select><label>TIME</label><input id="fTime" type="time"><button class="primary" onclick="addTask()">Add to mission</button></div>`)}
function addTask(){let title=$("#fTask").value.trim();if(!title)return toast("Enter a task name");state.tasks.unshift({id:Date.now(),title,sub:$("#fSub").value,time:$("#fTime").value,done:false});save();closeModal();renderPlanner();renderDash();toast("Mission added")}
function renderPlanner(){let x=$("#plannerList");if(!state.tasks.length){x.innerHTML='<div class="empty">No tasks yet. Add your first mission.</div>';return}x.innerHTML=state.tasks.map(t=>`<div class="task ${t.done?"done":""}"><div class="task-left"><button class="check" onclick="toggleTask(${t.id})">${t.done?"✓":""}</button><div><div class="task-title">${t.title}</div><small>${t.sub}${t.time?" • "+t.time:""}</small></div></div><button class="ghost" onclick="delTask(${t.id})">Delete</button></div>`).join("")}
function toggleTask(id){let t=state.tasks.find(x=>x.id===id);t.done=!t.done;save();renderPlanner();renderDash()}
function delTask(id){state.tasks=state.tasks.filter(x=>x.id!==id);save();renderPlanner();renderDash()}

function openPyqModal(){openModal(`<h2>Log PYQ session</h2><div class="form"><label>SUBJECT</label><select id="pSub"><option>Physics</option><option>Chemistry</option><option>Mathematics</option></select><label>CHAPTER / UNIT</label><input id="pChap" placeholder="Chapter name"><label>ATTEMPTED</label><input id="pAtt" type="number" min="0" value="20"><label>CORRECT</label><input id="pCor" type="number" min="0" value="15"><button class="primary" onclick="addPyq()">Save PYQ data</button></div>`)}
function addPyq(){let a=+$("#pAtt").value,c=+$("#pCor").value;if(c>a)return toast("Correct cannot exceed attempted");state.pyqs.unshift({sub:$("#pSub").value,chap:$("#pChap").value||"Untitled",a,c,date:new Date().toLocaleDateString()});save();closeModal();renderPyq();toast("PYQ session saved")}
function renderPyq(){let a=state.pyqs.reduce((s,x)=>s+x.a,0),c=state.pyqs.reduce((s,x)=>s+x.c,0);$("#pyqAttempted").textContent=a;$("#pyqCorrect").textContent=c;$("#pyqAccuracy").textContent=(a?Math.round(c/a*100):0)+"%";$("#pyqList").innerHTML=state.pyqs.length?state.pyqs.map(x=>`<div class="pyq-card"><span class="accuracy">${x.a?Math.round(x.c/x.a*100):0}%</span><b>${x.chap}</b><small>${x.sub} • ${x.a} attempted • ${x.c} correct • ${x.date}</small></div>`).join(""):'<div class="empty">No PYQ sessions logged.</div>'}

function renderDash(){let total=54,done=Object.values(state.completed).filter(Boolean).length,overall=Math.round(done/total*100);$("#doneCount").textContent=done;$("#taskCount").textContent=state.tasks.length;$("#streakCount").textContent=state.streak||0;$("#hoursCount").textContent=Math.floor(state.focus/60)+"m";$("#overallPct").textContent=overall+"%";$("#heroRing").style.background=`conic-gradient(var(--accent) ${overall*3.6}deg,#252d3e 0)`;$("#todayTasks").innerHTML=state.tasks.slice(0,5).map(t=>`<div class="task ${t.done?"done":""}"><div><b>${t.title}</b><small>${t.sub}${t.time?" • "+t.time:""}</small></div><span class="tag">${t.done?"DONE":"NEXT"}</span></div>`).join("")||'<div class="empty">Your mission board is empty.</div>';$("#subjectPulse").innerHTML=["Physics","Chemistry","Mathematics"].map(s=>`<div class="bar-row"><div class="bar-head"><span>${s}</span><b>${progress(s)}%</b></div><div class="bar"><i style="width:${progress(s)}%"></i></div></div>`).join("")}
function renderAnalytics(){let ps=["Physics","Chemistry","Mathematics"];$("#analyticsBars").innerHTML=ps.map(s=>`<div class="bar-row"><div class="bar-head"><span>${s}</span><b>${progress(s)}%</b></div><div class="bar"><i style="width:${progress(s)}%"></i></div></div>`).join("");let weak=ps.slice().sort((a,b)=>progress(a)-progress(b))[0];$("#insights").innerHTML=`<div class="insight">🎯 <b>Weakest subject:</b> ${weak} (${progress(weak)}%). Give it your next focused block.</div><div class="insight">📝 <b>PYQ accuracy:</b> ${$("#pyqAccuracy").textContent}. Review incorrect questions, not just the score.</div><div class="insight">🔥 <b>Consistency:</b> ${state.streak||0} day streak. Keep the chain alive.</div>`}

function openModal(body){$("#modalBody").innerHTML=body;$("#modal").classList.add("show")}function closeModal(){$("#modal").classList.remove("show")}$("#modal").onclick=e=>{if(e.target.id==="modal")closeModal()};

function fmt(s){return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}
function updateTimer(){ $("#timerDisplay").textContent=fmt(leftSec);$("#timerBar").style.width=(100*(1-leftSec/totalSec))+"%"; }
$$(".mode").forEach(m=>m.onclick=()=>{if(timer)clearInterval(timer);timer=null;$$(".mode").forEach(x=>x.classList.remove("active"));m.classList.add("active");totalSec=leftSec=+m.dataset.min*60;updateTimer();$("#timerStatus").textContent="Ready when you are."});
$("#startTimer").onclick=()=>{if(timer)return;$("#timerStatus").textContent="Deep work in progress…";timer=setInterval(()=>{if(leftSec<=0){clearInterval(timer);timer=null;state.focus+=Math.round(totalSec/60);state.streak=Math.max(1,state.streak||0);save();renderDash();$("#timerStatus").textContent="Session complete. Nice work! 🔥";toast("Focus session complete");return}leftSec--;updateTimer()},1000)};
$("#resetTimer").onclick=()=>{if(timer)clearInterval(timer);timer=null;leftSec=totalSec;updateTimer();$("#timerStatus").textContent="Ready when you are."};

$("#themeBtn").onclick=()=>{document.body.classList.toggle("light");$("#themeBtn").textContent=document.body.classList.contains("light")?"☀":"☾"};
renderSyllabus();renderPlanner();renderPyq();renderDash();updateTimer();
