const SYLLABUS = {
Physics:[
["Units & Measurements","Units, SI units, least count, significant figures, errors, dimensions and dimensional analysis."],
["Kinematics","Reference frame, straight-line motion, graphs, uniformly accelerated motion, relative velocity, projectile and circular motion."],
["Laws of Motion","Newton's laws, momentum, impulse, friction, equilibrium and centripetal-force applications."],
["Work, Energy & Power","Work, kinetic/potential energy, work-energy theorem, power, conservation, springs, vertical circle and collisions."],
["Rotational Motion","Centre of mass, torque, angular momentum, moment of inertia, axes theorems, rigid-body equilibrium and rotation."],
["Gravitation","Universal gravitation, variation of g, Kepler's laws, potential, escape velocity and satellites."],
["Properties of Solids & Liquids","Elasticity, fluid pressure, viscosity, Bernoulli, surface tension, heat, calorimetry and heat transfer."],
["Thermodynamics","Thermal equilibrium, zeroth/first/second laws, heat, work, internal energy and isothermal/adiabatic processes."],
["Kinetic Theory of Gases","Perfect gas, kinetic theory, pressure, temperature, RMS speed, degrees of freedom, equipartition and mean free path."],
["Oscillations & Waves","Periodic motion, SHM, spring, pendulum, wave motion, superposition, standing waves and beats."],
["Electrostatics","Charge, Coulomb law, electric field/flux, Gauss law, potential, dipole, conductors, dielectrics and capacitors."],
["Current Electricity","Drift velocity, Ohm law, resistance, power, cells, Kirchhoff laws, Wheatstone bridge and metre bridge."],
["Magnetic Effects of Current & Magnetism","Biot-Savart, Ampere law, magnetic force, current loops, galvanometer, magnetic dipoles and magnetic materials."],
["Electromagnetic Induction & Alternating Currents","Faraday/Lenz laws, eddy currents, inductance, AC values, reactance, LCR, resonance, generator and transformer."],
["Electromagnetic Waves","Displacement current, EM-wave characteristics, transverse nature, spectrum and applications."],
["Optics","Mirrors, refraction, lenses, TIR, prism, microscope/telescope, wavefronts, interference, diffraction and polarization."],
["Dual Nature of Matter & Radiation","Photoelectric effect, Einstein equation, particle nature of light and de Broglie matter waves."],
["Atoms & Nuclei","Rutherford/Bohr models, energy levels, hydrogen spectrum, nuclear composition, mass defect, binding energy, fission and fusion."],
["Electronic Devices","Semiconductors, diodes, rectifiers, LED, photodiode, solar cell, Zener regulator and logic gates."],
["Experimental Skills","Vernier calipers, screw gauge, pendulum, metre scale, elasticity, surface tension, viscosity, sound, calorimetry, bridges, galvanometer, optics and diode experiments."]
],
Chemistry:[
["Some Basic Concepts in Chemistry","Matter, Dalton theory, atoms/molecules, laws of combination, atomic/molecular masses, mole concept, formulae, equations and stoichiometry."],
["Atomic Structure","Radiation, photoelectric effect, hydrogen spectrum, Bohr model, dual nature, de Broglie, uncertainty, quantum model, orbitals, quantum numbers and electronic configuration."],
["Chemical Bonding & Molecular Structure","Ionic/covalent bonding, lattice enthalpy, electronegativity, Fajan rule, VSEPR, hybridization, resonance, MOT, bond order, metallic and hydrogen bonding."],
["Chemical Thermodynamics","System/surroundings, properties, entropy, processes, first/second laws, enthalpy, Hess law, Gibbs energy and spontaneity."],
["Solutions","Concentration terms, vapour pressure, Raoult law, ideal/non-ideal solutions, colligative properties and van't Hoff factor."],
["Equilibrium","Physical/chemical equilibrium, Henry law, Kp/Kc, Le Chatelier, acids/bases, pH, hydrolysis, Ksp and buffers."],
["Redox Reactions & Electrochemistry","Oxidation/reduction, oxidation number, balancing, conductance, Kohlrausch law, cells, electrode potential, Nernst equation, batteries and fuel cells."],
["Chemical Kinetics","Rate, factors, order/molecularity, rate law, zero/first order, half-life, Arrhenius theory and activation energy."],
["Classification of Elements & Periodicity","Modern periodic law, s/p/d/f blocks and trends in radii, ionization enthalpy, electron gain enthalpy, valence and reactivity."],
["p-Block Elements","Groups 13–18, electronic configuration, general physical/chemical trends and unique first-element behaviour."],
["d- & f-Block Elements","Transition elements, configurations, properties, oxidation states, colour, catalysis, magnetism, complexes, alloys, K2Cr2O7, KMnO4 and lanthanoid/actinoid chemistry."],
["Coordination Compounds","Werner theory, ligands, coordination number, denticity, chelation, nomenclature, isomerism, bonding, crystal field basics, colour and magnetism."],
["Purification & Characterisation of Organic Compounds","Crystallization, sublimation, distillation, extraction, chromatography, qualitative/quantitative analysis and empirical/molecular formula calculations."],
["Some Basic Principles of Organic Chemistry","Carbon tetravalency, hybridization, functional groups, homologous series, isomerism, nomenclature, bond fission, intermediates, electronic effects and reaction types."],
["Hydrocarbons","Alkanes, alkenes, alkynes and aromatic hydrocarbons: nomenclature, preparation, properties, reactions, mechanisms, ozonolysis and polymerization."],
["Organic Compounds Containing Halogens","Preparation, properties, reactions, C-X bond, substitution mechanisms and uses/environmental effects of selected compounds."],
["Organic Compounds Containing Oxygen","Alcohols, phenols, ethers, aldehydes, ketones and carboxylic acids: preparation, properties, reactions and characteristic mechanisms/tests."],
["Organic Compounds Containing Nitrogen","Amines: preparation, nomenclature, classification, structure, basicity and identification; diazonium salts and synthetic importance."],
["Biomolecules","Carbohydrates, proteins, amino acids, peptide bonds, protein structures, denaturation, enzymes, vitamins, DNA/RNA and hormones."],
["Principles Related to Practical Chemistry","Functional-group/element detection, preparation chemistry, titrimetric principles, qualitative salt analysis and selected practical experiments."]
],
Mathematics:[
["Sets, Relations & Functions","Sets, operations, power set, relations, equivalence relations, functions, one-one/into/onto and composition."],
["Complex Numbers & Quadratic Equations","Complex numbers, Argand diagram, modulus/argument, algebra, quadratic equations, roots, nature of roots and formation of equations."],
["Matrices & Determinants","Matrices, operations, determinants of order 2/3, area by determinants, adjoint/inverse, consistency and simultaneous equations."],
["Permutations & Combinations","Fundamental principle of counting, permutations, combinations and simple applications."],
["Binomial Theorem & Simple Applications","Positive integral index, general term, middle term and simple applications."],
["Sequence & Series","Arithmetic/geometric progressions, insertion of means and relation between A.M. and G.M."],
["Limit, Continuity & Differentiability","Functions and graphs, limits, continuity, differentiation, composite/implicit functions, second derivatives, monotonicity, maxima/minima and rates."],
["Integral Calculus","Antiderivatives, standard integrals, substitution, parts, partial fractions, trig identities, FTC, definite integrals and areas."],
["Differential Equations","Order/degree, separation of variables and homogeneous/linear differential equations."],
["Coordinate Geometry","Coordinates, distance/section formula, locus, lines, angles, concurrence, triangle centres, circle and conic sections."],
["Three Dimensional Geometry","3D coordinates, distance, section formula, direction ratios/cosines, line equations, skew lines and shortest distance."],
["Vector Algebra","Vectors/scalars, addition, components in 2D/3D and scalar/vector products."],
["Statistics & Probability","Dispersion, mean/median/mode, standard deviation, variance, mean deviation, probability theorems, Bayes theorem and random-variable distribution."],
["Trigonometry","Trigonometric identities/functions and inverse trigonometric functions with their properties."]
]
};